apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-IMGVERSION
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: vIMGVERSION
    spec:
      containers:
      - name: helloworld
        image: durgaoct1989/helloworld:IMGVERSION
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
