apiVersion: v1
kind: Service
metadata:
 name: helloworld
 labels:
  app: helloworld
spec:
 type: NodePort
 ports:
 - port: 5000
   name: http
 selector:
   app: helloworld
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: helloworld
          servicePort: 5000
---

